"""Bot decks this build can actually pilot.

DO NOT EDIT BY HAND. Regenerate with::

    python scripts/generate_bot_decks.py

Generated from the ``[Deck(...)]`` attributes of the bundled WindBot executors,
cross checked against the deck files in ``Decks/``. An executor without its deck
file, or a deck file without an executor, is left out: WindBot would fall back
to a random deck and the player would get something they did not choose.
"""

# WindBot deck key -> deck file stem in Decks/
KEY_TO_DECK_FILE: dict[str, str] = {
    'ABC': 'AI_ABC',
    'Altergeist': 'AI_Altergeist',
    'Blackwing': 'AI_Blackwing',
    'Blue-Eyes': 'AI_BlueEyes',
    'BlueEyesMaxDragon': 'AI_BlueEyesMaxDragon',
    'Brave': 'AI_Brave',
    'Burn': 'AI_Burn',
    'ChainBurn': 'AI_ChainBurn',
    'CyberDragon': 'AI_CyberDragon',
    'DarkMagician': 'AI_DarkMagician',
    'Dogmatika': 'AI_Dogmatika',
    'Dragun': 'AI_Dragun',
    'Dragunity': 'AI_Dragunity',
    'Evilswarm': 'AI_Evilswarm',
    'FamiliarPossessed': 'AI_FamiliarPossessed',
    'Frog': 'AI_Frog',
    'Gravekeeper': 'AI_Gravekeeper',
    'Graydle': 'AI_Graydle',
    'GrenMajuThunderBoarder': 'AI_GrenMajuThunderBoarder',
    'Horus': 'AI_Horus',
    'Kashtira': 'AI_Kashtira',
    'Level VIII': 'AI_Level8',
    'Lightsworn': 'AI_Lightsworn',
    'LightswornShaddoldinosour': 'AI_LightswornShaddoldinosour',
    'MathMech': 'AI_Mathmech',
    'MokeyMokey': 'AI_MokeyMokey',
    'MokeyMokeyKing': 'AI_MokeyMokeyKing',
    'Nekroz': 'AI_Nekroz',
    'OldSchool': 'AI_OldSchool',
    'Orcust': 'AI_Orcust',
    'Phantasm': 'AI_Phantasm',
    'PureWinds': 'AI_PureWinds',
    'Qliphort': 'AI_Qliphort',
    'Rainbow': 'AI_Rainbow',
    'Rank V': 'AI_Rank5',
    'ST1732': 'AI_ST1732',
    'Salamangreat': 'AI_Salamangreat',
    'SkyStriker': 'AI_SkyStriker',
    'Swordsoul': 'AI_Swordsoul',
    'Tearlaments': 'AI_Tearlaments',
    'ThunderDragon': 'AI_ThunderDragon',
    'TimeThief': 'AI_Timethief',
    'Toadally Awesome': 'AI_ToadallyAwesome',
    'Trickstar': 'AI_Trickstar',
    'Witchcraft': 'AI_Witchcraft',
    'Yosenju': 'AI_Yosenju',
    'Zexal Weapons': 'AI_ZexalWeapons',
    'Zoodiac': 'AI_Zoodiac',
    '[HealingJAM]': 'AI_[HealingJAM]',
    '[ImaginaryArk]': 'AI_[ImaginaryArk]',
}

# Difficulty as the executor declares it: Easy, Normal or NotFinished.
KEY_TO_LEVEL: dict[str, str] = {
    'ABC': 'Normal',
    'Altergeist': 'Normal',
    'Blackwing': 'NotFinished',
    'Blue-Eyes': 'Normal',
    'BlueEyesMaxDragon': 'Normal',
    'Brave': 'Normal',
    'Burn': 'Easy',
    'ChainBurn': 'Normal',
    'CyberDragon': 'NotFinished',
    'DarkMagician': 'Normal',
    'Dogmatika': 'Normal',
    'Dragun': 'Normal',
    'Dragunity': 'Normal',
    'Evilswarm': 'NotFinished',
    'FamiliarPossessed': 'Normal',
    'Frog': 'Easy',
    'Gravekeeper': 'NotFinished',
    'Graydle': 'NotFinished',
    'GrenMajuThunderBoarder': 'Normal',
    'Horus': 'Easy',
    'Kashtira': 'Normal',
    'Level VIII': 'Normal',
    'Lightsworn': 'NotFinished',
    'LightswornShaddoldinosour': 'Normal',
    'MathMech': 'Normal',
    'MokeyMokey': 'Easy',
    'MokeyMokeyKing': 'Easy',
    'Nekroz': 'NotFinished',
    'OldSchool': 'Easy',
    'Orcust': 'Normal',
    'Phantasm': 'Normal',
    'PureWinds': 'Normal',
    'Qliphort': 'Normal',
    'Rainbow': 'Normal',
    'Rank V': 'Normal',
    'ST1732': 'Normal',
    'Salamangreat': 'Normal',
    'SkyStriker': 'Normal',
    'Swordsoul': 'Normal',
    'Tearlaments': 'Normal',
    'ThunderDragon': 'Normal',
    'TimeThief': 'Normal',
    'Toadally Awesome': 'Normal',
    'Trickstar': 'Normal',
    'Witchcraft': 'Normal',
    'Yosenju': 'Normal',
    'Zexal Weapons': 'Normal',
    'Zoodiac': 'Normal',
    '[HealingJAM]': 'Normal',
    '[ImaginaryArk]': 'Normal',
}

DECK_FILE_TO_KEY: dict[str, str] = {
    'AI_ABC': 'ABC',
    'AI_Altergeist': 'Altergeist',
    'AI_Blackwing': 'Blackwing',
    'AI_BlueEyes': 'Blue-Eyes',
    'AI_BlueEyesMaxDragon': 'BlueEyesMaxDragon',
    'AI_Brave': 'Brave',
    'AI_Burn': 'Burn',
    'AI_ChainBurn': 'ChainBurn',
    'AI_CyberDragon': 'CyberDragon',
    'AI_DarkMagician': 'DarkMagician',
    'AI_Dogmatika': 'Dogmatika',
    'AI_Dragun': 'Dragun',
    'AI_Dragunity': 'Dragunity',
    'AI_Evilswarm': 'Evilswarm',
    'AI_FamiliarPossessed': 'FamiliarPossessed',
    'AI_Frog': 'Frog',
    'AI_Gravekeeper': 'Gravekeeper',
    'AI_Graydle': 'Graydle',
    'AI_GrenMajuThunderBoarder': 'GrenMajuThunderBoarder',
    'AI_Horus': 'Horus',
    'AI_Kashtira': 'Kashtira',
    'AI_Level8': 'Level VIII',
    'AI_Lightsworn': 'Lightsworn',
    'AI_LightswornShaddoldinosour': 'LightswornShaddoldinosour',
    'AI_Mathmech': 'MathMech',
    'AI_MokeyMokey': 'MokeyMokey',
    'AI_MokeyMokeyKing': 'MokeyMokeyKing',
    'AI_Nekroz': 'Nekroz',
    'AI_OldSchool': 'OldSchool',
    'AI_Orcust': 'Orcust',
    'AI_Phantasm': 'Phantasm',
    'AI_PureWinds': 'PureWinds',
    'AI_Qliphort': 'Qliphort',
    'AI_Rainbow': 'Rainbow',
    'AI_Rank5': 'Rank V',
    'AI_ST1732': 'ST1732',
    'AI_Salamangreat': 'Salamangreat',
    'AI_SkyStriker': 'SkyStriker',
    'AI_Swordsoul': 'Swordsoul',
    'AI_Tearlaments': 'Tearlaments',
    'AI_ThunderDragon': 'ThunderDragon',
    'AI_Timethief': 'TimeThief',
    'AI_ToadallyAwesome': 'Toadally Awesome',
    'AI_Trickstar': 'Trickstar',
    'AI_Witchcraft': 'Witchcraft',
    'AI_Yosenju': 'Yosenju',
    'AI_ZexalWeapons': 'Zexal Weapons',
    'AI_Zoodiac': 'Zoodiac',
    'AI_[HealingJAM]': '[HealingJAM]',
    'AI_[ImaginaryArk]': '[ImaginaryArk]',
}
