"""Duel (game) message ids, generated from ocgcore's ocgapi_constants.h.

DO NOT EDIT BY HAND. Regenerate with::

    python scripts/generate_message_constants.py

This is the single source of truth for duel message ids. Client handlers
(``ui.duel_messages``) and the bundled server (``server.duel``) must both import
from here rather than re-declaring their own numbers.
"""

from enum import IntEnum


class MSG(IntEnum):
    """Duel message ids as defined by ocgcore."""

    RETRY = 1
    HINT = 2
    WAITING = 3
    START = 4
    WIN = 5
    UPDATE_DATA = 6
    UPDATE_CARD = 7
    REQUEST_DECK = 8
    SELECT_BATTLECMD = 10
    SELECT_IDLECMD = 11
    SELECT_EFFECTYN = 12
    SELECT_YESNO = 13
    SELECT_OPTION = 14
    SELECT_CARD = 15
    SELECT_CHAIN = 16
    SELECT_PLACE = 18
    SELECT_POSITION = 19
    SELECT_TRIBUTE = 20
    SORT_CHAIN = 21
    SELECT_COUNTER = 22
    SELECT_SUM = 23
    SELECT_DISFIELD = 24
    SORT_CARD = 25
    SELECT_UNSELECT_CARD = 26
    CONFIRM_DECKTOP = 30
    CONFIRM_CARDS = 31
    SHUFFLE_DECK = 32
    SHUFFLE_HAND = 33
    REFRESH_DECK = 34
    SWAP_GRAVE_DECK = 35
    SHUFFLE_SET_CARD = 36
    REVERSE_DECK = 37
    DECK_TOP = 38
    SHUFFLE_EXTRA = 39
    NEW_TURN = 40
    NEW_PHASE = 41
    CONFIRM_EXTRATOP = 42
    MOVE = 50
    POS_CHANGE = 53
    SET = 54
    SWAP = 55
    FIELD_DISABLED = 56
    SUMMONING = 60
    SUMMONED = 61
    SPSUMMONING = 62
    SPSUMMONED = 63
    FLIPSUMMONING = 64
    FLIPSUMMONED = 65
    CHAINING = 70
    CHAINED = 71
    CHAIN_SOLVING = 72
    CHAIN_SOLVED = 73
    CHAIN_END = 74
    CHAIN_NEGATED = 75
    CHAIN_DISABLED = 76
    CARD_SELECTED = 80
    RANDOM_SELECTED = 81
    BECOME_TARGET = 83
    DRAW = 90
    DAMAGE = 91
    RECOVER = 92
    EQUIP = 93
    LPUPDATE = 94
    UNEQUIP = 95
    CARD_TARGET = 96
    CANCEL_TARGET = 97
    PAY_LPCOST = 100
    ADD_COUNTER = 101
    REMOVE_COUNTER = 102
    ATTACK = 110
    BATTLE = 111
    ATTACK_DISABLED = 112
    DAMAGE_STEP_START = 113
    DAMAGE_STEP_END = 114
    MISSED_EFFECT = 120
    BE_CHAIN_TARGET = 121
    CREATE_RELATION = 122
    RELEASE_RELATION = 123
    TOSS_COIN = 130
    TOSS_DICE = 131
    ROCK_PAPER_SCISSORS = 132
    HAND_RES = 133
    ANNOUNCE_RACE = 140
    ANNOUNCE_ATTRIB = 141
    ANNOUNCE_CARD = 142
    ANNOUNCE_NUMBER = 143
    CARD_HINT = 160
    TAG_SWAP = 161
    RELOAD_FIELD = 162
    AI_NAME = 163
    SHOW_HINT = 164
    PLAYER_HINT = 165
    MATCH_KILL = 170
    CUSTOM_MSG = 180
    REMOVE_CARDS = 190


# Module level aliases matching the C names, for readability at call sites.
MSG_RETRY = MSG.RETRY
MSG_HINT = MSG.HINT
MSG_WAITING = MSG.WAITING
MSG_START = MSG.START
MSG_WIN = MSG.WIN
MSG_UPDATE_DATA = MSG.UPDATE_DATA
MSG_UPDATE_CARD = MSG.UPDATE_CARD
MSG_REQUEST_DECK = MSG.REQUEST_DECK
MSG_SELECT_BATTLECMD = MSG.SELECT_BATTLECMD
MSG_SELECT_IDLECMD = MSG.SELECT_IDLECMD
MSG_SELECT_EFFECTYN = MSG.SELECT_EFFECTYN
MSG_SELECT_YESNO = MSG.SELECT_YESNO
MSG_SELECT_OPTION = MSG.SELECT_OPTION
MSG_SELECT_CARD = MSG.SELECT_CARD
MSG_SELECT_CHAIN = MSG.SELECT_CHAIN
MSG_SELECT_PLACE = MSG.SELECT_PLACE
MSG_SELECT_POSITION = MSG.SELECT_POSITION
MSG_SELECT_TRIBUTE = MSG.SELECT_TRIBUTE
MSG_SORT_CHAIN = MSG.SORT_CHAIN
MSG_SELECT_COUNTER = MSG.SELECT_COUNTER
MSG_SELECT_SUM = MSG.SELECT_SUM
MSG_SELECT_DISFIELD = MSG.SELECT_DISFIELD
MSG_SORT_CARD = MSG.SORT_CARD
MSG_SELECT_UNSELECT_CARD = MSG.SELECT_UNSELECT_CARD
MSG_CONFIRM_DECKTOP = MSG.CONFIRM_DECKTOP
MSG_CONFIRM_CARDS = MSG.CONFIRM_CARDS
MSG_SHUFFLE_DECK = MSG.SHUFFLE_DECK
MSG_SHUFFLE_HAND = MSG.SHUFFLE_HAND
MSG_REFRESH_DECK = MSG.REFRESH_DECK
MSG_SWAP_GRAVE_DECK = MSG.SWAP_GRAVE_DECK
MSG_SHUFFLE_SET_CARD = MSG.SHUFFLE_SET_CARD
MSG_REVERSE_DECK = MSG.REVERSE_DECK
MSG_DECK_TOP = MSG.DECK_TOP
MSG_SHUFFLE_EXTRA = MSG.SHUFFLE_EXTRA
MSG_NEW_TURN = MSG.NEW_TURN
MSG_NEW_PHASE = MSG.NEW_PHASE
MSG_CONFIRM_EXTRATOP = MSG.CONFIRM_EXTRATOP
MSG_MOVE = MSG.MOVE
MSG_POS_CHANGE = MSG.POS_CHANGE
MSG_SET = MSG.SET
MSG_SWAP = MSG.SWAP
MSG_FIELD_DISABLED = MSG.FIELD_DISABLED
MSG_SUMMONING = MSG.SUMMONING
MSG_SUMMONED = MSG.SUMMONED
MSG_SPSUMMONING = MSG.SPSUMMONING
MSG_SPSUMMONED = MSG.SPSUMMONED
MSG_FLIPSUMMONING = MSG.FLIPSUMMONING
MSG_FLIPSUMMONED = MSG.FLIPSUMMONED
MSG_CHAINING = MSG.CHAINING
MSG_CHAINED = MSG.CHAINED
MSG_CHAIN_SOLVING = MSG.CHAIN_SOLVING
MSG_CHAIN_SOLVED = MSG.CHAIN_SOLVED
MSG_CHAIN_END = MSG.CHAIN_END
MSG_CHAIN_NEGATED = MSG.CHAIN_NEGATED
MSG_CHAIN_DISABLED = MSG.CHAIN_DISABLED
MSG_CARD_SELECTED = MSG.CARD_SELECTED
MSG_RANDOM_SELECTED = MSG.RANDOM_SELECTED
MSG_BECOME_TARGET = MSG.BECOME_TARGET
MSG_DRAW = MSG.DRAW
MSG_DAMAGE = MSG.DAMAGE
MSG_RECOVER = MSG.RECOVER
MSG_EQUIP = MSG.EQUIP
MSG_LPUPDATE = MSG.LPUPDATE
MSG_UNEQUIP = MSG.UNEQUIP
MSG_CARD_TARGET = MSG.CARD_TARGET
MSG_CANCEL_TARGET = MSG.CANCEL_TARGET
MSG_PAY_LPCOST = MSG.PAY_LPCOST
MSG_ADD_COUNTER = MSG.ADD_COUNTER
MSG_REMOVE_COUNTER = MSG.REMOVE_COUNTER
MSG_ATTACK = MSG.ATTACK
MSG_BATTLE = MSG.BATTLE
MSG_ATTACK_DISABLED = MSG.ATTACK_DISABLED
MSG_DAMAGE_STEP_START = MSG.DAMAGE_STEP_START
MSG_DAMAGE_STEP_END = MSG.DAMAGE_STEP_END
MSG_MISSED_EFFECT = MSG.MISSED_EFFECT
MSG_BE_CHAIN_TARGET = MSG.BE_CHAIN_TARGET
MSG_CREATE_RELATION = MSG.CREATE_RELATION
MSG_RELEASE_RELATION = MSG.RELEASE_RELATION
MSG_TOSS_COIN = MSG.TOSS_COIN
MSG_TOSS_DICE = MSG.TOSS_DICE
MSG_ROCK_PAPER_SCISSORS = MSG.ROCK_PAPER_SCISSORS
MSG_HAND_RES = MSG.HAND_RES
MSG_ANNOUNCE_RACE = MSG.ANNOUNCE_RACE
MSG_ANNOUNCE_ATTRIB = MSG.ANNOUNCE_ATTRIB
MSG_ANNOUNCE_CARD = MSG.ANNOUNCE_CARD
MSG_ANNOUNCE_NUMBER = MSG.ANNOUNCE_NUMBER
MSG_CARD_HINT = MSG.CARD_HINT
MSG_TAG_SWAP = MSG.TAG_SWAP
MSG_RELOAD_FIELD = MSG.RELOAD_FIELD
MSG_AI_NAME = MSG.AI_NAME
MSG_SHOW_HINT = MSG.SHOW_HINT
MSG_PLAYER_HINT = MSG.PLAYER_HINT
MSG_MATCH_KILL = MSG.MATCH_KILL
MSG_CUSTOM_MSG = MSG.CUSTOM_MSG
MSG_REMOVE_CARDS = MSG.REMOVE_CARDS

MESSAGE_NAMES: dict[int, str] = {int(message): message.name for message in MSG}

ALL_MESSAGE_IDS: frozenset[int] = frozenset(int(message) for message in MSG)
