"""Generate an English template from bundled game strings.

This is separate from Babel UI extraction. Game strings are stored in
EDOPro-style strings.conf files and are addressed by category + numeric id.

Usage:
    python scripts/game_strings_template.py
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).parent.parent
DEFAULT_INPUT = ROOT / "src" / "data" / "locales" / "en" / "strings.conf"
DEFAULT_OUTPUT = ROOT / "src" / "data" / "locales" / "en" / "strings.template.conf"
IGNORED_CATEGORIES = {"setcode"}


@dataclass(frozen=True)
class GameString:
    category: str
    raw_id: str
    numeric_id: int
    text: str


def parse_game_strings(path: Path) -> list[GameString]:
    """Return all translatable game strings from a strings.conf file."""
    strings: list[GameString] = []
    with path.open("r", encoding="utf-8") as fp:
        for line in fp:
            line = line.rstrip("\n")
            if not line.startswith("!"):
                continue

            parts = line[1:].split(" ", 2)
            if len(parts) != 3:
                continue

            category, raw_id, text = parts
            if category in IGNORED_CATEGORIES:
                continue

            try:
                numeric_id = int(raw_id, 16) if raw_id.startswith("0x") else int(raw_id)
            except ValueError:
                continue

            strings.append(
                GameString(
                    category=category,
                    raw_id=raw_id,
                    numeric_id=numeric_id,
                    text=text.replace("\xa0", " "),
                )
            )
    return strings


def render_template(strings: list[GameString], source: Path) -> str:
    lines = [
        "# YuGiOhAccess English game strings template",
        f"# Source: {source.as_posix()}",
        "# Generated by scripts/game_strings_template.py",
        "# Format: !<category> <id> <English string>",
        "",
    ]

    current_category: str | None = None
    for item in strings:
        if item.category != current_category:
            if current_category is not None:
                lines.append("")
            lines.append(f"#{item.category}")
            current_category = item.category
        lines.append(f"!{item.category} {item.raw_id} {item.text}")

    lines.append("")
    return "\n".join(lines)


def _source_label(input_path: Path) -> Path:
    """Path to record in the template header, relative to the repo when possible."""
    try:
        return input_path.relative_to(ROOT)
    except ValueError:
        return input_path


def write_template(input_path: Path = DEFAULT_INPUT, output_path: Path = DEFAULT_OUTPUT) -> int:
    strings = parse_game_strings(input_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_template(strings, _source_label(input_path)), encoding="utf-8")
    return len(strings)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an English template from the bundled game strings.conf file."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="English game strings.conf to read.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Template file to write.",
    )
    args = parser.parse_args()

    count = write_template(args.input, args.output)
    print(f"Wrote {count} English game strings to {args.output}")


if __name__ == "__main__":
    main()
